In [5]:
import pandas as pd
df=pd.read_csv("./test_data.csv")
df.head()

,PATIENT_ID,PWEIGHTSTAT,PWEIGHTCHNG,PHEALTHSTAT,PHOUSINGSEC,PWORKSTAT,XPTIMEADDRMM_RC,PWORKHRS_RC,PMARITAL_RC,PHOMEOWN_RC,...,PDFSMKTCSA,PDMAFASTFD,PDMAPIZZA,PDMACONV,PDMAFSREST,PDMHFASTFD,PDMHDELIVR,PDMHHTSERV,PDMHCOOK,PDAFV
0,227,4,1,2,2,1,3,3,1,1,...,1,1,0,0,1,1,0,1,2,4
1,331,2,2,2,3,1,1,2,1,1,...,1,1,0,0,0,0,0,0,5,5
2,353,4,1,2,2,1,3,2,1,1,...,2,1,1,0,0,1,0,0,6,3
3,483,5,1,4,1,1,4,4,2,1,...,1,0,0,0,1,0,0,0,4,4
4,957,4,1,3,3,7,1,-1,4,2,...,1,0,1,0,0,0,1,0,6,4

In [15]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.cluster import KMeans


X = df.drop(['PATIENT_ID','PWEIGHTSTAT'],axis=1).values.tolist()
y = df['PWEIGHTSTAT'].values.tolist()

estimators = [('k_means_iris_8', KMeans(n_clusters=8)),
              ('k_means_iris_3', KMeans(n_clusters=3)),
              ('k_means_iris_bad_init', KMeans(n_clusters=3, n_init=1,
                                               init='random'))]

fignum = 1
titles = ['8 clusters', '3 clusters', '3 clusters, bad initialization']

for name, est in estimators:
    fig = plt.figure(fignum, figsize=(4, 3))
    ax = Axes3D(fig, rect=[0, 0, .95, 1], elev=48, azim=134)
    est.fit(X)
    labels = est.labels_

    ax.scatter(X[:][3], X[:][0], X[:][2],
               c=labels.astype(float), edgecolor='k')

    ax.w_xaxis.set_ticklabels([])
    ax.w_yaxis.set_ticklabels([])
    ax.w_zaxis.set_ticklabels([])
    ax.set_xlabel('Petal width')
    ax.set_ylabel('Sepal length')
    ax.set_zlabel('Petal length')
    ax.set_title(titles[fignum - 1])
    ax.dist = 12
    fignum = fignum + 1